### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by raffdp** [elmarquez/four#6]
This is a repeat of the recently closed question regarding issue #5

I have only just came across this page and would like to use it in a project. 

I am new to node.js and I am having trouble getting the demo up and running so it would be nice to see it running.

The second part of that question is also valid for me.

**Comment by raffdp** [comment]
It's okay, I got it running

**Comment by Alexinjin** [comment]
How did you get the demo running? Would you mind sharing the basic idea? I was not able to run `yarn build`
